# TODO FOURTH PRIORITY

# TODO FOLLOW THE RULE OF CRUD, CREATE/READ/UPDATE/DELETE

def createDelivery(orderId, user=""):
    # OPEN AND READ DELIVERY FILE
    # FIND THE LATEST ID, ADD 1 TO IT
    # PERSONAL CAN BE BLANK IF PASS IN NOTHING
    # STATUS WILL BE NEW
    # FEEDBACK ALSO WILL BE ""
    return None


def viewDelivery():
    # READ AND OPEN FILE OF DELIVERY
    # LIST IT OUT
    # ASK USER IF YOU WANT TO DO SUBSEQUENT ACTION, UPDATE DELIVERY MAN, UPDATE FEEDBACK ETC
    return None


def assignDeliveryStaff(deliveryId, userId):
    # READ AND OPEN FILE OF DELIVERY
    # READ AND OPEN FILE OF USER
    # LET THE USER KEY IN USERID
    # SEE IF THE USER EXIST IN THE FILE, IF NOT, THEN CALL THE USER TO KEY AGAIN OR QUIT
    # IF USER EXIST, UPDATE THE FILE
    return None


def createDeliveryFeedback(deliveryId, feedback):
    # READ AND OPEN FILE OF DELIVERY
    # FIND THE ROW OF DELIVERY INFO BASED ON THE DELIVERYID
    # WRITE INTO THE FILE AND SAVE THE FILE
    return None